devtools:
    livereload:
        enabled: true
    restart:
        enabled: true
server:
    port: 8081
spring:
    datasource:
        username: root
        password: 123456
        url:  jdbc:mysql://localhost:3306/world?serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
    web:
        resources:
            static-locations: classpath:/templates/
    thymeleaf:
        encoding: utf-8
    sql:
        init:
            schema-locations: classpath:schema.sql
mybatis-plus:
            mapper-locations: classpath:/dao/*.xml
#logging:
#    file:
#        path: logs/info.log
#    logback:
#        rollingpolicy:
#            max-history: 2
#            max-file-size: 1MB
